language: node_js
node_js:
  - "10"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
  - pip install --user --upgrade b2
script:
  - yarn lint
  - yarn build
jobs:
  include:
    - stage: Publish staging
      if: type = push AND fork = false AND tag IS blank AND branch = develop
      script:
        - b2 authorize-account ${B2_STAGING_KEY_ID} ${B2_STAGING_KEY}
        - b2 sync --keepDays 30 --replaceNewer dist/ b2://plumealerts/staging/
        - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
        - curl --ftp-create-dirs -T dist/ --key /tmp/sftp_rsa sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_HOST}${SFTP_PATH}
cache:
  yarn: true
