language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn install
  - pip install --user --upgrade b2
script:
  - yarn lint

jobs:
  include:
    # Staging
    - stage: buildStaging
      name: "Building Staging"
      if: tag IS blank AND branch = master
      script: yarn build:staging
    - stage: deployStaging
      name: "Deploying Staging"
      if: tag IS blank AND branch = master
      script: ./scripts/staging/deploy.sh
    # Release
    - stage: build
      name: "Building"
      if: tag IS present AND branch = master
      script: yarn build
    - stage: deploy
      name: "Deploying"
      if: tag IS present AND branch = master
      script: ./scripts/release/deploy.sh
