language: node_js
node_js:
  - "10"

install:
  - yarn install
  - pip install --user --upgrade b2
script:
  - yarn lint
  - $TRAVIS_BRANCH == "develop" && yarn build:staging
  - $TRAVIS_BRANCH == "master" && yarn build
# Temp fix switch  to build stages

cache: yarn

before_deploy:
  - b2 authorize-account ${B2_STAGING_KEY_ID} ${B2_STAGING_KEY}
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-keyscan ${SFTP_HOST} >> ~/.ssh/known_hosts
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  ## Deploy to staging
  # Deploy to B2
  - provider: script
    skip_cleanup: true
    script: b2 sync --keepDays 30 --replaceNewer dist/ b2://plumealerts/staging/
    on:
      branch: develop
  # Deploy to server
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after dist/ ${SFTP_USER}@${SFTP_HOST}:${SFTP_PATH}
    on:
      branch: develop
