language: node_js
node_js:
  - "10"

cache: yarn

stages:
  - name: test
  # Staging
  - name: buildStaging
    if: tag IS blank AND branch = master
  # Release
  - name: build
    if: tag IS present AND branch = master

jobs:
  include:
    - stage: test
      script: yarn lint
    # Staging
    - stage: buildStaging
      name: "Building Staging"
      script: yarn build:staging && ./scripts/staging/deploy.sh
    # Release
    - stage: build
      name: "Building"
      script: yarn build &&  ./scripts/release/deploy.sh
