language: node_js
node_js:
  - "10"

cache: yarn

stages:
  - name: test
  # Staging
  - name: buildStaging
    if: tag IS blank AND branch = master
  - name: deployStaging
    if: tag IS blank AND branch = master AND type = push

  # Release
  - name: build
    if: tag IS present AND branch = master
  - name: deploy
    if: tag IS present AND branch = master AND type = push

jobs:
  include:
    - stage: test
      script: yarn lint
    # Staging
    - stage: buildStaging
      name: "Building Staging"
      script: yarn build:staging
    - stage: deployStaging
      name: "Deploy Staging"
      script: ./scripts/staging/deploy.sh
    # Release
    - stage: build
      name: "Building"
      script: yarn build
    - stage: deploy
      name: "Deploy"
      script: ./scripts/release/deploy.sh
