language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn install
  - pip install --user --upgrade b2
script:
  - yarn lint

stages:
  # Staging
  - name: buildStaging
  - name: deployStaging
    if: tag IS blank AND branch = master
  # Release
  - name: build
  - name: deploy
    if: tag IS present AND branch = master


jobs:
  include:
    # Staging
    - stage: buildStaging
      name: "Building Staging"
      script: yarn build:staging
    - stage: deployStaging
      name: "Deploying Staging"
      script: ./scripts/staging/deploy.sh
    # Release
    - stage: build
      name: "Building"
      script: yarn build
    - stage: deploy
      name: "Deploying"
      script: ./scripts/release/deploy.sh
