name: CI
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout and setup
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          version: 3.7

      # Install dependencies
      - name: Install B2
        run: pip install --upgrade b2
      - name: Install yarn
        run: npm install -g yarn

      - name: npm install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build:staging

      - name: deploy
        run: |
          b2 authorize-account ${{ secrets.B2_STAGING_KEY_ID }} ${{ secrets.B2_STAGING_APPLICATION_KEY }}
          b2 sync --keepDays 14 --replaceNewer dist/ b2://plumealerts/staging/

          echo "${{ secrets.SFTP_STAGING_KEY }}" | base64 --decode >/tmp/deploy_rsa
          eval $(ssh-agent -s)
          ssh-keyscan ${{ secrets.SFTP_STAGING_HOST }} >> ~/.ssh/known_hosts
          chmod 600 /tmp/deploy_rsa
          ssh-add /tmp/deploy_rsa

          rsync -r --delete-after dist/ ${{ secrets.SFTP_STAGING_USER }}@${{ secrets.SFTP_STAGING_HOST }}:${{ secrets.SFTP_STAGING_PATH }}
        env:
          CI: true
