name: CI
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout and setup
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      # Install dependencies
      - name: Install B2
        run: pip install --upgrade b2
      - name: Install yarn
        run: npm install -g yarn

      - name: npm install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build:staging

      - name: deploy backblaze
        run: |
          b2 authorize-account ${{ secrets.B2_STAGING_KEY_ID }} ${{ secrets.B2_STAGING_APPLICATION_KEY }}
          b2 sync --keepDays 14 --replaceNewer dist/ b2://plumealerts/staging/

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.STAGING_SSH_PRIVATE }}
          public-key: ${{ secrets.STAGING_SSH_PUBLIC }}
          known-hosts: ${{ secrets.SFTP_STAGING_HOST }}
      - name: Install packages
        run: apt install openssh-client rsync
      - name: Deploy
          run: |
          rsync -r --delete-after dist/index.html ${{ secrets.SFTP_STAGING_USER }}@${{ secrets.SFTP_STAGING_HOST }}:${{ secrets.SFTP_STAGING_PATH }}
